import '../core/dock/dock_position.dart';
import '../core/modules/module_category.dart';
import '../core/modules/module_health.dart';
import '../core/modules/module_manifest.dart';
import '../core/modules/module_permissions.dart';
import '../core/modules/module_status.dart';

class DemoModules {
  static const List<ModuleManifest> all = [
    ModuleManifest(
      id: 'module_hub',
      name: 'Module Hub',
      description:
          'System core registry for registering, inspecting, enabling and docking dashboard modules.',
      category: ModuleCategory.systemCore,
      version: '0.1.0',
      status: ModuleStatus.enabled,
      enabled: true,
      dockable: false,
      defaultDockPosition: DockPosition.fullscreen,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.omegaOsAccess),
      ],
      installPath: 'lib/features/modules',
      omegaOsPath: 'docs/architecture/module_hub',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.healthy,
        lastCheckedLabel: 'Placeholder: just now',
        backendStatus: 'UI shell only',
        errors: [],
        warnings: ['No real loader wired yet.'],
        nextAction: 'Connect manifest loading in the next phase.',
      ),
      tags: ['core', 'registry', 'dashboard'],
      notes: 'This module is the hub for the dashboard module shell.',
    ),
    ModuleManifest(
      id: 'funding_grants_command_centre',
      name: 'Funding Grants Command Centre',
      description:
          'Tracks grants, funding applications, readiness, evidence packs and review actions.',
      category: ModuleCategory.grantsFunding,
      version: '0.1.0',
      status: ModuleStatus.installed,
      enabled: false,
      dockable: true,
      defaultDockPosition: DockPosition.left,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.fileWrite),
        ModulePermission(type: ModulePermissionType.calendarAccess),
        ModulePermission(type: ModulePermissionType.internetAccess),
      ],
      installPath: 'modules/funding_grants_command_centre',
      omegaOsPath: 'OMEGA_OS/MODULES/FUNDING_GRANTS_COMMAND_CENTRE',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.warning,
        lastCheckedLabel: 'Placeholder: today',
        backendStatus: 'Mock registry only',
        errors: [],
        warnings: ['Awaiting manifest persistence.'],
        nextAction: 'Review funding module metadata.',
      ),
      tags: ['funding', 'grants'],
    ),
    ModuleManifest(
      id: 'gaia_voice_assistant',
      name: 'Gaia Voice Assistant',
      description:
          'Voice capture and review-first assistant for fast command drafting and local save workflows.',
      category: ModuleCategory.aiAutomation,
      version: '0.1.0',
      status: ModuleStatus.enabled,
      enabled: true,
      dockable: true,
      defaultDockPosition: DockPosition.right,
      permissions: [
        ModulePermission(type: ModulePermissionType.microphone),
        ModulePermission(type: ModulePermissionType.speaker),
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.fileWrite),
      ],
      installPath: 'modules/gaia_voice_assistant',
      omegaOsPath: 'OMEGA_OS/MODULES/GAIA_VOICE_ASSISTANT',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.healthy,
        lastCheckedLabel: 'Placeholder: today',
        backendStatus: 'Local UI bridge active',
        errors: [],
        warnings: [],
        nextAction: 'Keep transcript review local-first.',
      ),
      tags: ['voice', 'assistant'],
    ),
    ModuleManifest(
      id: 'knowledge_engine',
      name: 'Knowledge Engine',
      description:
          'Searches local knowledge, maps research notes, and supports future documentation workflows.',
      category: ModuleCategory.knowledgeResearch,
      version: '0.1.0',
      status: ModuleStatus.planned,
      enabled: false,
      dockable: true,
      defaultDockPosition: DockPosition.bottom,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.repoAccess),
      ],
      installPath: 'modules/knowledge_engine',
      omegaOsPath: 'OMEGA_OS/MODULES/KNOWLEDGE_ENGINE',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.unknown,
        lastCheckedLabel: 'Placeholder: not checked',
        backendStatus: 'Manifest only',
        errors: [],
        warnings: ['Planned shell only.'],
        nextAction: 'Load local manifests later.',
      ),
      tags: ['knowledge', 'research'],
    ),
    ModuleManifest(
      id: 'meeting_system',
      name: 'Meeting System',
      description:
          'Meeting planning, decisions, actions, follow-ups and templates for calm review.',
      category: ModuleCategory.projectManagement,
      version: '0.1.0',
      status: ModuleStatus.installed,
      enabled: true,
      dockable: false,
      defaultDockPosition: DockPosition.fullscreen,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.fileWrite),
      ],
      installPath: 'modules/meeting_system',
      omegaOsPath: 'OMEGA_OS/MODULES/MEETING_SYSTEM',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.healthy,
        lastCheckedLabel: 'Placeholder: today',
        backendStatus: 'Screen shell ready',
        errors: [],
        warnings: [],
        nextAction: 'Connect to meeting records later.',
      ),
      tags: ['meetings', 'actions'],
    ),
    ModuleManifest(
      id: 'NE_OBSIDIAN_SYNC_MODULE',
      name: 'Obsidian Sync',
      description:
          'Links dashboard records to a local Obsidian workflow for note review and future sync.',
      category: ModuleCategory.knowledgeResearch,
      version: '0.1.0',
      status: ModuleStatus.disabled,
      enabled: false,
      dockable: true,
      defaultDockPosition: DockPosition.bottom,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.fileWrite),
      ],
      installPath: 'modules/NE_OBSIDIAN_SYNC_MODULE',
      omegaOsPath: 'OMEGA_OS/MODULES/OBSIDIAN_SYNC',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.offline,
        lastCheckedLabel: 'Placeholder: not checked',
        backendStatus: 'Dormant',
        errors: [],
        warnings: ['Not connected yet.'],
        nextAction: 'Keep as a future sync bridge.',
      ),
      tags: ['notes', 'sync'],
    ),
    ModuleManifest(
      id: 'NE_REPO_INTELLIGENCE_BRIDGE',
      name: 'Repo Intelligence Bridge',
      description:
          'Read-only bridge for repository awareness, status, and future local research flows.',
      category: ModuleCategory.security,
      version: '0.1.0',
      status: ModuleStatus.disabled,
      enabled: false,
      dockable: true,
      defaultDockPosition: DockPosition.right,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.repoAccess),
      ],
      installPath: 'modules/NE_REPO_INTELLIGENCE_BRIDGE',
      omegaOsPath: 'OMEGA_OS/MODULES/REPO_INTELLIGENCE_BRIDGE',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.warning,
        lastCheckedLabel: 'Placeholder: not checked',
        backendStatus: 'Bridge stub',
        errors: [],
        warnings: ['Read-only placeholder only.'],
        nextAction: 'Connect to local repo data later.',
      ),
      tags: ['repo', 'bridge'],
    ),
    ModuleManifest(
      id: 'NEW_EARTH_ALEXA_VOICE_GATEWAY_MODULE',
      name: 'Alexa Voice Gateway',
      description:
          'Guarded local gateway for voice triggers and future Alexa-connected handoff workflows.',
      category: ModuleCategory.voiceHardware,
      version: '0.1.0',
      status: ModuleStatus.experimental,
      enabled: false,
      dockable: true,
      defaultDockPosition: DockPosition.right,
      permissions: [
        ModulePermission(type: ModulePermissionType.microphone),
        ModulePermission(type: ModulePermissionType.speaker),
        ModulePermission(type: ModulePermissionType.localNetwork),
      ],
      installPath: 'modules/NEW_EARTH_ALEXA_VOICE_GATEWAY_MODULE',
      omegaOsPath: 'OMEGA_OS/MODULES/ALEXA_VOICE_GATEWAY',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.degraded,
        lastCheckedLabel: 'Placeholder: today',
        backendStatus: 'Gateway not running',
        errors: [],
        warnings: ['External voice bridge not connected.'],
        nextAction: 'Keep the handoff surface visible only.',
      ),
      tags: ['voice', 'gateway'],
    ),
    ModuleManifest(
      id: 'new_earth_command_deck',
      name: 'New Earth Command Deck',
      description:
          'Command surface for quick actions, dashboard shortcuts and future tactile controls.',
      category: ModuleCategory.systemCore,
      version: '0.1.0',
      status: ModuleStatus.installed,
      enabled: true,
      dockable: true,
      defaultDockPosition: DockPosition.left,
      permissions: [
        ModulePermission(type: ModulePermissionType.appLaunch),
        ModulePermission(type: ModulePermissionType.fileRead),
      ],
      installPath: 'modules/new_earth_command_deck',
      omegaOsPath: 'OMEGA_OS/MODULES/NEW_EARTH_COMMAND_DECK',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.healthy,
        lastCheckedLabel: 'Placeholder: today',
        backendStatus: 'Dashboard shortcut surface',
        errors: [],
        warnings: [],
        nextAction: 'Later connect to the action registry.',
      ),
      tags: ['command', 'shortcuts'],
    ),
    ModuleManifest(
      id: 'new_earth_launchpad_module',
      name: 'Launchpad',
      description:
          'Campaign and launch planning shell for awareness, delivery, and future public launch workflows.',
      category: ModuleCategory.communityOutreach,
      version: '0.1.0',
      status: ModuleStatus.installed,
      enabled: true,
      dockable: true,
      defaultDockPosition: DockPosition.left,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.fileWrite),
      ],
      installPath: 'modules/new_earth_launchpad_module',
      omegaOsPath: 'OMEGA_OS/MODULES/NEW_EARTH_LAUNCHPAD',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.healthy,
        lastCheckedLabel: 'Placeholder: today',
        backendStatus: 'Launch shell ready',
        errors: [],
        warnings: [],
        nextAction: 'Connect campaign data later.',
      ),
      tags: ['launch', 'campaign'],
    ),
    ModuleManifest(
      id: 'project_repo_bridge',
      name: 'Project Repo Bridge',
      description:
          'Bridges project context to repository awareness for future source-linked dashboards.',
      category: ModuleCategory.security,
      version: '0.1.0',
      status: ModuleStatus.disabled,
      enabled: false,
      dockable: true,
      defaultDockPosition: DockPosition.bottom,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.repoAccess),
      ],
      installPath: 'modules/project_repo_bridge',
      omegaOsPath: 'OMEGA_OS/MODULES/PROJECT_REPO_BRIDGE',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.unknown,
        lastCheckedLabel: 'Placeholder: not checked',
        backendStatus: 'Bridge placeholder',
        errors: [],
        warnings: ['Awaiting repo mapping.'],
        nextAction: 'Keep as read-only metadata for now.',
      ),
      tags: ['project', 'repo'],
    ),
    ModuleManifest(
      id: 'repo_reserch_engine',
      name: 'Repo Research Engine',
      description:
          'Repo research and scan shell for change awareness, summaries, and future evidence packs.',
      category: ModuleCategory.knowledgeResearch,
      version: '0.1.0',
      status: ModuleStatus.installed,
      enabled: false,
      dockable: true,
      defaultDockPosition: DockPosition.bottom,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.repoAccess),
      ],
      installPath: 'modules/repo_reserch_engine',
      omegaOsPath: 'OMEGA_OS/MODULES/REPO_RESEARCH_ENGINE',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.warning,
        lastCheckedLabel: 'Placeholder: today',
        backendStatus: 'Shell only',
        errors: [],
        warnings: ['Name preserved from current folder.'],
        nextAction: 'Later phase can correct the source name if needed.',
      ),
      tags: ['repo', 'research'],
    ),
    ModuleManifest(
      id: 'system_backup',
      name: 'System Backup',
      description:
          'Local backup and recovery control surface for protected folders and restore readiness.',
      category: ModuleCategory.backupRecovery,
      version: '0.1.0',
      status: ModuleStatus.enabled,
      enabled: true,
      dockable: true,
      defaultDockPosition: DockPosition.bottom,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.fileWrite),
        ModulePermission(type: ModulePermissionType.omegaOsAccess),
      ],
      installPath: 'modules/system_backup',
      omegaOsPath: 'OMEGA_OS/MODULES/SYSTEM_BACKUP',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.healthy,
        lastCheckedLabel: 'Placeholder: today',
        backendStatus: 'Recovery placeholder',
        errors: [],
        warnings: ['No live backup runner connected.'],
        nextAction: 'Attach persistence later.',
      ),
      tags: ['backup', 'recovery'],
    ),
    ModuleManifest(
      id: 'voice_intelligence_module',
      name: 'Voice Intelligence',
      description:
          'Voice analysis shell for transcripts, conversation history, and future speech intelligence.',
      category: ModuleCategory.aiAutomation,
      version: '0.1.0',
      status: ModuleStatus.enabled,
      enabled: true,
      dockable: true,
      defaultDockPosition: DockPosition.right,
      permissions: [
        ModulePermission(type: ModulePermissionType.microphone),
        ModulePermission(type: ModulePermissionType.speaker),
        ModulePermission(type: ModulePermissionType.fileRead),
      ],
      installPath: 'modules/voice_intelligence_module',
      omegaOsPath: 'OMEGA_OS/MODULES/VOICE_INTELLIGENCE_MODULE',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.healthy,
        lastCheckedLabel: 'Placeholder: today',
        backendStatus: 'Voice shell ready',
        errors: [],
        warnings: [],
        nextAction: 'Keep speech processing local-first.',
      ),
      tags: ['voice', 'intelligence'],
    ),
    ModuleManifest(
      id: '00_NEW_EARTH_OMEGA_MODULE_HUB_UI',
      name: 'Omega Module Hub UI',
      description:
          'Imported reference pack for the Module Hub shell and the source of the dashboard scaffold.',
      category: ModuleCategory.systemCore,
      version: '0.1.0',
      status: ModuleStatus.installed,
      enabled: true,
      dockable: false,
      defaultDockPosition: DockPosition.fullscreen,
      permissions: [
        ModulePermission(type: ModulePermissionType.fileRead),
        ModulePermission(type: ModulePermissionType.omegaOsAccess),
      ],
      installPath: 'modules/00_NEW_EARTH_OMEGA_MODULE_HUB_UI',
      omegaOsPath: 'OMEGA_OS/MODULES/00_NEW_EARTH_OMEGA_MODULE_HUB_UI',
      health: ModuleHealthSnapshot(
        state: ModuleHealthState.healthy,
        lastCheckedLabel: 'Imported reference pack',
        backendStatus: 'Documentation only',
        errors: [],
        warnings: [],
        nextAction: 'Use as reference, not runtime code.',
      ),
      tags: ['reference', 'module-hub'],
      notes: 'Imported pack used as a design and structure reference.',
    ),
  ];
}
